name: 'Parse Comment for Carrot Command'
description: 'Parses a comment to see if it matches the Carrot command format:

    #carrot({test_name}, {test_input_key}, {eval_input_key})

    where {test_name} is the unique name of the test, 

    {test_input_key} is the input in the test wdl to which the generated docker image should be 
    supplied (can be left blank), and
    
    {eval_input_key} is the input in the eval wdl to which the generated docker image should be 
    supplied (can be left blank)
    
    Ex. #carrot(my_cool_test, in_gatk_docker, in_gatk_docker2)
    
    Ex. #carrot(my_cool_test, , in_gatk_docker2)
    
    Ex. #carrot(my_cool_test, in_gatk_docker, )'
inputs:
    software-name:
        description: 'The name of the software in this repository, as it is written in the 
            software record for this repository in the CARROT database'
        required: true
    github-token:
        description: 'The GitHub token for using the GitHub API.  Generated automatically for the 
            Actions workflow.'
        required: true
    topic-name:
        description: 'The Google Cloud PubSub topic name for the topic we will publish the message 
            to to start the test'
        required: true
    sa-key:
        description: 'The Service Account key JSON for the service account that has publish 
            permissions for the PubSub topic'
runs:
    using: 'node12'
    main: 'index.js'
